version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQLDB_USER} -p${MYSQLDB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: car-sharing
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_PORT}/${MYSQLDB_DATABASE}",
              "spring.datasource.username": "${MYSQLDB_USER}",
              "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
              "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
              "jwt.secret": "${JWT_SECRET}",
              "jwt.expiration": "${JWT_EXPIRATION}",
              "bot.token": "${TELEGRAM_BOT_TOKEN}",
              "bot.name": "${TELEGRAM_BOT_USERNAME}",
              "admin.chat.id": "${TELEGRAM_ADMIN_CHAT_ID}",
              "stripe.api.key": "${STRIPE_API_KEY}",
              "stripe.webhook.secret": "{STRIPE_WEBHOOK_SECRET}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
